CREATE TABLE octagon.users (
    UserID INT AUTO_INCREMENT PRIMARY KEY,
    Firstname VARCHAR(100) NOT NULL,
    Lastname VARCHAR(100) NOT NULL,
    Username VARCHAR(100) UNIQUE NOT NULL,
    Email VARCHAR(100) UNIQUE NOT NULL,
    Password VARCHAR(255) NOT NULL,
    Address TEXT,
    City VARCHAR(100)
);

CREATE TABLE posts (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    Title VARCHAR(255) NOT NULL,
    Body TEXT NOT NULL
);

CREATE TABLE history (
    ID INT AUTO_INCREMENT PRIMARY KEY,
    PostID INT NOT NULL,
    PersonID INT NOT NULL,
    FOREIGN KEY (PostID) REFERENCES posts(ID) ON DELETE CASCADE,
    FOREIGN KEY (PersonID) REFERENCES users(UserID) ON DELETE CASCADE
);
